AWSTemplateFormatVersion: '2010-09-09'
Description: Stack para criar os recursos necessarios da solucao de Remote Deployment do Service Catalog. 
https://github.com/alexandreags/aws-service-catalog-remote-deployment
Transform: AWS::LanguageExtensions
Parameters:
  BucketName:
    Type: String
    Description: "Nome do Bucket de Deployment"
    ConstraintDescription: Preencher o nome corretamente.
  OrgId:
    Type: String
    Description: "Nome do Bucket de Deployment"
    ConstraintDescription: Preencher o nome corretamente.
Resources:
  s3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join 
          - '-'
          - - !Ref BucketName
            - !Ref 'AWS::AccountId'
            - ServiceCatalog
      OwnershipControls:
        Rules:
        - ObjectOwnership: BucketOwnerPreferred
      AccessControl: AwsExecRead    
  s3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref s3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref s3Bucket
                - /*
            Principal: '*'
  s3Key:
    Type: 'AWS::KMS::Key'
    Properties:
      Description: !Join 
        - '-'
        - - 'Chave KMS para o bucket: '
          - !Ref BucketName
          - !Ref 'AWS::AccountId'
          - ServiceCatalog
      EnableKeyRotation: true
      PendingWindowInDays: 20
      KeyPolicy:
        Version: 2012-10-17
        Id: key-s3-1
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::111122223333:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Allow administration of the key
            Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::111122223333:user/Alice'
            Action:
              - 'kms:Create*'
              - 'kms:Describe*'
              - 'kms:Enable*'
              - 'kms:List*'
              - 'kms:Put*'
              - 'kms:Update*'
              - 'kms:Revoke*'
              - 'kms:Disable*'
              - 'kms:Get*'
              - 'kms:Delete*'
              - 'kms:ScheduleKeyDeletion'
              - 'kms:CancelKeyDeletion'
            Resource: '*'
          - Sid: Allow use of the key
            Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::111122223333:user/Bob'
            Action:
              - 'kms:DescribeKey'
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey'
              - 'kms:GenerateDataKeyWithoutPlaintext'
            Resource: '*'